# Config file for [Air](https://github.com/air-verse/air) in TOML format

# Working directory
# . or absolute path, please note that the directories following must be under root.
root = "."
tmp_dir = "tmp"

[build]
# Add additional arguments when running binary (bin/full_bin).
args_bin = []
# Binary file yields from `cmd`. change binary to `main.exe` if you using windows
bin = "./tmp/main"
# Just plain old shell command. You could use `make` as well. change binary to `main.exe` if you using windows
cmd = "go build -race -o ./tmp/main ./src"
# It's not necessary to trigger build each time file changes if it's too frequent.
delay = 1000 # ms
# Ignore these filename extensions or directories.
exclude_dir = ["assets", "tmp", "vendor"]
# Exclude files.
exclude_file = []
# Exclude specific regular expressions.
exclude_regex = ["_test\\.go"]
# Exclude unchanged files.
exclude_unchanged = false
# Follow symlink for directories
follow_symlink = false
# Customize binary, can setup environment variables when run your app.
full_bin = ""
# Watch these directories if you specified.
include_dir = []
# Watch these filename extensions.
include_ext = ["go", "tpl", "tmpl", "env"]
# Watch these files.
include_file = []
# Delay after sending Interrupt signal
kill_delay = "0s"
# This log file places in your tmp_dir.
log = "build-errors.log"
# Poll files for changes instead of using fsnotify.
poll = false
# Poll interval (defaults to the minimum interval of 500ms).
poll_interval = 0 # ms
# Array of commands to run after ^C
post_cmd = []
# Array of commands to run before each build
pre_cmd = []
# Rerun binary or not
rerun = false
# Delay after each execution
rerun_delay = 500
# Send Interrupt signal before killing process (windows does not support this feature)
send_interrupt = false
# Stop running old binary when build errors occur.
stop_on_error = false

[color]
# Customize each part's color. If no color found, use the raw app log.
app = ""
build = "yellow"
main = "magenta"
runner = "green"
watcher = "cyan"

[log]
# Only show main log (silences watcher, build, runner)
main_only = false
# Show log time
time = false

[misc]
# Delete tmp directory on exit
clean_on_exit = true

# Enable live-reloading on the browser.
[proxy]
app_port = 0
enabled = false
proxy_port = 0

[screen]
clear_on_rebuild = true
keep_scroll = true
